### ISSUE TITLE
Error in fread during parsing

### ISSUE THREAD

**Issue by jimijimiyo** [achetverikov/visual_search_db#12]
Transformed old configs to the new format and encountered an error (new config attached, note it is in txt - github do not allow to attach yaml files):

Processing configuration file data/chetverikov_kristjansson_2015/import_conf.yaml
Configuration file is correct.
Error in fread(file.path(folder, conf$Experiment$required$trials_file)) : 
  'input' must be a single character string containing a file name, a command, full path to a file, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or the input data itself

[import_conf.txt](https://github.com/achetverikov/visual_search_db/files/1313837/import_conf.txt)

**Comment by achetverikov** [comment]
Yeah, I know, I haven't finished all the code changes necessary for the new config format. I also want to simplify the config a bit, because right now it has too many sections in the meta part. That makes writing import/export scripts more complex and also makes filling in the config fields look like a hellish task. That would scare off the people who want to add something.

**Comment by jimijimiyo** [comment]
OK. I agree that it looks a bit scary, but too much simplification will lead to data loss. On the other hand, if we'll add some interface in the future it will not be such a frightening task, even with this amount of sections. I mean, look at Zenodo upload page - it has many metadata fields, but the majority is optional and it looks fine.

**Comment by achetverikov** [comment]
Should be working now =)
